/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chuongnq.ui;

import static chuongnq.ui.ListDemo.listPetNames;
import javax.swing.ImageIcon;
import javax.swing.JList;

/**
 *
 * @author ChươngNguyễnQuốc
 */
public class ListDemo extends javax.swing.JFrame {

    /**
     * Creates new form ListDemo
     */
    ImageIcon pig = new ImageIcon(getClass().getResource("/Image/pig.png"));
    ImageIcon bird = new ImageIcon(getClass().getResource("/Image/bird.png"));
    ImageIcon rabbit = new ImageIcon(getClass().getResource("/Image/rabbit.png"));
    ImageIcon dog = new ImageIcon(getClass().getResource("/Image/dog.png"));
    ImageIcon cat = new ImageIcon(getClass().getResource("/Image/cat.png"));
    String petName[] = {"Bird", "Cat", "Dog", "Rabbit", "Pig"};

    public ListDemo() {
        initComponents();
        listPetNames = new JList(petName);
        listPetNames.setSelectedIndex(0);
        if (listPetNames.getSelectedIndex() == 0) {
            lbPetPic.setIcon(bird);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPetNames = new javax.swing.JList<>();
        lbPetPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listPetNames.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bird", "Cat", "Dog", "Rabbit", "Pig" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listPetNames.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPetNames.setToolTipText("");
        listPetNames.setRequestFocusEnabled(false);
        listPetNames.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPetNamesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listPetNames);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbPetPic, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPetPic, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listPetNamesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPetNamesMouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 1) {
            JList target = (JList) evt.getSource();
            int index = target.locationToIndex(evt.getPoint());
            if (index >= 0) {
                Object item = target.getModel().getElementAt(index);
                if (item.toString().equals("Pig")) {
                    lbPetPic.setIcon(pig);
                } else if (item.toString().equals("Bird")) {
                    lbPetPic.setIcon(bird);
                } else if (item.toString().equals("Rabbit")) {
                    lbPetPic.setIcon(rabbit);
                } else if (item.toString().equals("Dog")) {
                    lbPetPic.setIcon(dog);
                } else if (item.toString().equals("Cat")) {
                    lbPetPic.setIcon(cat);
                }
            }
        }
    }//GEN-LAST:event_listPetNamesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListDemo().setVisible(true);
                new ComboBoxDemo().setVisible(true);
            }
        });
//        String petName[] = {"Bird", "Cat", "Dog", "Rabbit", "Pig"};
//        JFrame f = new JFrame();
//        
//        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        listPetNames = new JList(petName);
//        JScrollPane scrollPane = new JScrollPane(listPetNames);
//
//        Container contentPane = f.getContentPane();
//        contentPane.add(scrollPane,BorderLayout.WEST);
//        contentPane.add()
//        
//        f.setSize(1007, 687);
//        f.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbPetPic;
    public static javax.swing.JList<String> listPetNames;
    // End of variables declaration//GEN-END:variables
}
