/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chuongnq.ui;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author ChươngNguyễnQuốc
 */
public class EditableTree extends javax.swing.JFrame {

    /**
     * Creates new form EditableTree
     */
    public EditableTree() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        tfAdd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRemove.setText("Select node and click here to remove from tree");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAdd.setText("Add to Tree");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tfAdd.setText("Add new node here and click Add to Tree button");
        tfAdd.setToolTipText("");
        tfAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAddFocusLost(evt);
            }
        });
        tfAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfAddKeyPressed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Java Tree Example");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Resources");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Web Sites");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("JavaSoft");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Gameplan");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Magazines");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("abc");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Books");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Specical Edition Using Java 1.2");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Tools");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("JBuilder");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Visual J++");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Visual Age for Java");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Apptivity");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tfAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd))
            .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(tfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tfAdd.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAddFocusGained
        // TODO add your handling code here:
        if (tfAdd.getText().equals("Add new node here and click Add to Tree button")) {
            tfAdd.setText("");
        }
    }//GEN-LAST:event_tfAddFocusGained

    private void tfAddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAddFocusLost
        // TODO add your handling code here:
        if (tfAdd.getText().equals("")) {
            tfAdd.setText("Add new node here and click Add to Tree button");
        }
    }//GEN-LAST:event_tfAddFocusLost

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            if (tfAdd.getText().equals("Add new node here and click Add to Tree button")) {
                JOptionPane.showMessageDialog(rootPane, "You should enter name node you want to add");
            } else {
                DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();

                TreePath path = jTree1.getSelectionPath();
                MutableTreeNode node = (MutableTreeNode) path.getLastPathComponent();
                String addNode = tfAdd.getText();
                MutableTreeNode newNode = new DefaultMutableTreeNode(addNode);

                model.insertNodeInto(newNode, node, node.getChildCount());
                tfAdd.setText("Add new node here and click Add to Tree button");
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "You should choose node to add");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        try {
            DefaultMutableTreeNode node;
            DefaultTreeModel model = (DefaultTreeModel) (jTree1.getModel());
            TreePath[] paths = jTree1.getSelectionPaths();
            for (int i = 0; i < paths.length; i++) {
                node = (DefaultMutableTreeNode) (paths[i].getLastPathComponent());
                model.removeNodeFromParent(node);
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "You should select one node to remove");
        }

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void tfAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAddKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                if (tfAdd.getText().equals("Add new node here and click Add to Tree button")) {
                    JOptionPane.showMessageDialog(rootPane, "You should enter name node you want to add");
                } else {
                    DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();

                    TreePath path = jTree1.getSelectionPath();
                    MutableTreeNode node = (MutableTreeNode) path.getLastPathComponent();
                    String addNode = tfAdd.getText();
                    MutableTreeNode newNode = new DefaultMutableTreeNode(addNode);

                    model.insertNodeInto(newNode, node, node.getChildCount());
                    tfAdd.setText("Add new node here and click Add to Tree button");
                }
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(rootPane, "You should choose node to add");
            }
        }
    }//GEN-LAST:event_tfAddKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditableTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditableTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditableTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditableTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new EditableTree().setVisible(true);
                new EditableTree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTextField tfAdd;
    // End of variables declaration//GEN-END:variables
}
