/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chuongnq.dialog;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author ChươngNguyễnQuốc
 */
public class parentDialog extends javax.swing.JFrame {

    /**
     * Creates new form parentDialog
     */
    public parentDialog() {
        initComponents();

    }
    childrenDialog children = new childrenDialog();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblParent = new javax.swing.JTable();
        btnOpen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblParent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Stock one", "No1-Washington street", "11/05/2010", ""},
                {"2", "Stock two				", "372 Cave Town", "09/07/2011", "Good store"},
                {"3", "Stock three", "Nary angel", "13/05/2010", "Store dangerous materials"},
                {"4", "Stock four", "Twin tower", "04/07/2015", ""},
                {"5", "Stock five", "Victory anniversary", "08/12/2014", ""}
            },
            new String [] {
                "StockID", "StockName", "Address", "DateAvailable", "Note"
            }
        ));
        jScrollPane1.setViewportView(tblParent);

        btnOpen.setText("Open Item");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnOpen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnOpen)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:\
        try {
            try {

                int row = tblParent.getSelectedRow();
                TableModel model = tblParent.getModel();
                String id = model.getValueAt(row, 0).toString();
                String name = model.getValueAt(row, 1).toString();
                String address = model.getValueAt(row, 2).toString();
                String date = model.getValueAt(row, 3).toString();
                String note = model.getValueAt(row, 4).toString();

                children.setVisible(true);
                children.pack();
                children.setLocationRelativeTo(null);
                children.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                children.txtStockID.setText(id);
                children.txtStockName.setText(name);
                children.txtAddress.setText(address);
                children.txtDate.setText(date);
                children.txtNote.setText(note);

            } catch (NullPointerException ex) {
                int row = tblParent.getSelectedRow();
                TableModel model = tblParent.getModel();
                String id = model.getValueAt(row, 0).toString();
                String name = model.getValueAt(row, 1).toString();
                String address = model.getValueAt(row, 2).toString();
                String date = model.getValueAt(row, 3).toString();
                String note = model.getValueAt(row, 4).toString();

                children.setVisible(true);
                children.pack();
                children.setLocationRelativeTo(null);
                children.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                children.txtStockID.setText(id);
                children.txtStockName.setText(name);
                children.txtAddress.setText(address);
                children.txtDate.setText(date);
                children.txtNote.setText(" ");
            }
        } catch (IndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(tblParent, "Select first before click Open Item");
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parentDialog().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblParent;
    // End of variables declaration//GEN-END:variables
}
