/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chuongnq.ui;

import java.awt.Color;

/**
 *
 * @author ChươngNguyễnQuốc
 */
public class colorFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public colorFrame() {
        initComponents();
        lbColor.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbRed = new javax.swing.JRadioButton();
        rbBlue = new javax.swing.JRadioButton();
        rbGreen = new javax.swing.JRadioButton();
        rbBlack = new javax.swing.JRadioButton();
        lbColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbRed.setText("Red");
        rbRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRedActionPerformed(evt);
            }
        });

        rbBlue.setText("Blue");
        rbBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBlueActionPerformed(evt);
            }
        });

        rbGreen.setText("Green");
        rbGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGreenActionPerformed(evt);
            }
        });

        rbBlack.setText("Black");
        rbBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBlackActionPerformed(evt);
            }
        });

        lbColor.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbRed)
                    .addComponent(rbBlue)
                    .addComponent(rbGreen)
                    .addComponent(rbBlack))
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(lbColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbGreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbBlack)
                .addGap(18, 18, 18)
                .addComponent(lbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRedActionPerformed
        // TODO add your handling code here:
        if (rbRed.isSelected()) {
            rbBlue.setSelected(false);
            rbGreen.setSelected(false);
            rbBlack.setSelected(false);
            lbColor.setText("Red is selected");
            lbColor.setBackground(Color.red);
        }
    }//GEN-LAST:event_rbRedActionPerformed

    private void rbBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBlueActionPerformed
        // TODO add your handling code here:
        if (rbBlue.isSelected()) {
            rbRed.setSelected(false);
            rbGreen.setSelected(false);
            rbBlack.setSelected(false);
            lbColor.setText("Blue is selected");
            lbColor.setBackground(Color.blue);
        }
    }//GEN-LAST:event_rbBlueActionPerformed

    private void rbGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGreenActionPerformed
        // TODO add your handling code here:
        if (rbGreen.isSelected()) {
            rbRed.setSelected(false);
            rbBlue.setSelected(false);
            rbBlack.setSelected(false);
            lbColor.setText("Green is selected");
            lbColor.setBackground(Color.green);
        }
    }//GEN-LAST:event_rbGreenActionPerformed

    private void rbBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBlackActionPerformed
        // TODO add your handling code here:
        if (rbBlack.isSelected()) {
            rbRed.setSelected(false);
            rbBlue.setSelected(false);
            rbGreen.setSelected(false);
            lbColor.setText("Red is selected");
            lbColor.setBackground(Color.black);
        }
    }//GEN-LAST:event_rbBlackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(colorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(colorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(colorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(colorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new colorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbColor;
    private javax.swing.JRadioButton rbBlack;
    private javax.swing.JRadioButton rbBlue;
    private javax.swing.JRadioButton rbGreen;
    private javax.swing.JRadioButton rbRed;
    // End of variables declaration//GEN-END:variables
}
